// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC3FwveBAicuoUjuRfOLk82QCiyRb0NIo',
    appId: '1:869877265911:web:a6eed8ccde11b55531aaf2',
    messagingSenderId: '869877265911',
    projectId: 'orkestria-b25db',
    authDomain: 'orkestria-b25db.firebaseapp.com',
    storageBucket: 'orkestria-b25db.firebasestorage.app',
    measurementId: 'G-MSNM1SXW6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9IYizyMoNZ16JjhuQyc0q6DQGPh7tyIM',
    appId: '1:869877265911:android:0cceac499311a97231aaf2',
    messagingSenderId: '869877265911',
    projectId: 'orkestria-b25db',
    storageBucket: 'orkestria-b25db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzlTX4U7zgdkCxFneZmlnaClaSdHT2fRY',
    appId: '1:869877265911:ios:6b799ffab11be5da31aaf2',
    messagingSenderId: '869877265911',
    projectId: 'orkestria-b25db',
    storageBucket: 'orkestria-b25db.firebasestorage.app',
    iosBundleId: 'com.example.orkestria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzlTX4U7zgdkCxFneZmlnaClaSdHT2fRY',
    appId: '1:869877265911:ios:6b799ffab11be5da31aaf2',
    messagingSenderId: '869877265911',
    projectId: 'orkestria-b25db',
    storageBucket: 'orkestria-b25db.firebasestorage.app',
    iosBundleId: 'com.example.orkestria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC3FwveBAicuoUjuRfOLk82QCiyRb0NIo',
    appId: '1:869877265911:web:ce8d1201480c3da531aaf2',
    messagingSenderId: '869877265911',
    projectId: 'orkestria-b25db',
    authDomain: 'orkestria-b25db.firebaseapp.com',
    storageBucket: 'orkestria-b25db.firebasestorage.app',
    measurementId: 'G-LVF04S7TD8',
  );
}
